### PR TITLE
Checks for overflows for client max width and height

### LINKED ISSUE #263: dwl crashes when starting Slack with multiple monitors
## Info
dwl's commit: 72e0a560d9836c5e8658003f548203bcd722e565
wlroots version: 0.15.1
## Description
This only seems to crash dwl when using two monitors, and only when opening slack on a particular of those monitors. When opened on the other, slack crashes, but dwl does not. I'm running slack on Electron 18 (which runs with native wayland support). This was introduced with 72e0a560d9836c5e8658003f548203bcd722e565, and is fixed by reverting to the previous commit.

I get the following error when in stderr when it crashes:
```
dwl: render/wlr_renderer.c:155: wlr_render_rect: Assertion `box->width > 0 && box->height > 0' failed.
```

### PR DESCRIPTION
**Pull request by BenJarg**
Checks whether `min.width + (2 * c->bw)` and `min.height + (2 * c->bw)` causes overflow, which can cause negative width and height and crash some clients. Closes #263.

### CODE REVIEW

File: dwl.c [hunk 1]
```diff
@@ -387,9 +388,15 @@ applybounds(Client *c, struct wlr_box *bbox)
 	c->geom.width = MAX(min.width + (2 * c->bw), c->geom.width);
 	c->geom.height = MAX(min.height + (2 * c->bw), c->geom.height);
 	if (max.width > 0)
-		c->geom.width = MIN(max.width + (2 * c->bw), c->geom.width);
+		if ((2 * c->bw) > INT_MAX - max.width) // Checks for overflow
+			c->geom.width = c->geom.width;
+		else			
+			c->geom.width = MIN(max.width + (2 * c->bw), c->geom.width);
```
Comment (sevz17) [inline dwl.c:394]:
```suggestion
	if (max.width > 0 && !(2 * c->bw > INT_MAX - max.width)) // Checks for overflow
		c->geom.width = MIN(max.width + (2 * c->bw), c->geom.width);
```

File: dwl.c [hunk 2]
```diff
@@ -387,9 +388,15 @@ applybounds(Client *c, struct wlr_box *bbox)
...
 	if (max.height > 0)
-		c->geom.height = MIN(max.height + (2 * c->bw), c->geom.height);
+		if ((2 * c->bw) > INT_MAX - max.height) // Checks for overflow
+			c->geom.height = c->geom.height;
+		else			
+			c->geom.height = MIN(max.height + (2 * c->bw), c->geom.height);
```
Comment (sevz17) [inline dwl.c:399]:
```suggestion
	if (max.height > 0 && !(2 * c->bw > INT_MAX - max.height)) // Checks for overflow		
		c->geom.height = MIN(max.height + (2 * c->bw), c->geom.height);
```

**Review by sevz17 — CHANGES_REQUESTED** [review]

**Comment by sevz17** [comment]
Thanks!
